config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
  	sessions: "employees/sessions", registrations: "employees/registrations", passwords: "employees/passwords"
  }
  devise_for :companies, path: 'companies', controllers: {
  	sessions: "companies/sessions", registrations: "companies/registrations", passwords: "companies/passwords"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies, except: [:new, :create, :index]
  resources :employees, except: [:new, :create]
  root to: 'companies#index'

  resources :chats, except: [:edit]
  resources :messages, only: [:index, :new, :create]
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable, :trackable
    has_many :chats
    has_many :messages
end

app/controllers/employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

class Employees::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :birthday, :introduction, :admin])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true

class Employees::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  before_action :authenticate_employee!
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :name_kana, :birthday, :introduction, :admin])
  end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :authenticate_employee!

	def index
		@employee = Employee.all
	end

	def show
		@employee = Employee.find(params[:id])
		# @age = (Date.today.strftime("%Y/%m/%d").to_i - @employee[:birthday].strftime("%Y/%m/%d").to_i) / 10000
		@chat = Chat.all
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employee_path, notice: "情報を編集しました。"
		else
			render :edit
		end
	end

	def destroy
		employee = Employee.find(params[:id])
		employee.destroy
		redirect_to employee_path, notice: "情報を削除しました。"
	end

	private
	def employee_params
		params.require(:employee).permit(:name, :name_kana, :birthday, :introduction, :admin, :email, :password, :encrypted_password)
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= form_for (@employee) do |f| %>
				<table class="table">
					<tr>
						<td><%= f.label :名前 %></td>
						<td><%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "山田太郎", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :名前（カナ） %></td>
						<td><%= f.text_field :name_kana, autofocus: true, autocomplete: "naem_kana", placeholder: "ヤマダタロウ", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :生年月日 %></td>
						<td>
							<div>
					            <%= raw sprintf(f.date_select(
					                              :birthday,
					                              use_month_numbers: true,
					                              start_year:        1918,
					                              end_year:          (Time.now.year),
					                              default:           Date.new(1989, 1, 1),
					                              date_separator: '%s'), '年', '月') + '日' %>
					        </div>
					    </td>
					</tr>
					<tr>
						<td><%= f.label :メールアドレス %></td>
						<td><%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "example@example.com", class: "form-control" %></td>
					</tr>
					<tr>
						<td></td>
						<td><%= f.submit "情報を保存する", class: "btn btn-success" %></td>
					</tr>
				</table>
			<% end %>
		</div>
	</div>
</div>

app/views/employees/index.html.erb
<div class="container">
	<div class="row">
		<h3>登録者（求職者）一覧</h3>
		<table class="table">
			<tr>
				<th>ユーザ名</th>
				<th>メールアドレス</th>
				<th></th>
			</tr>
			<% @employee.each do |employee| %>
				<tr>
					<td><%= employee.name %></td>
					<td><%= employee.email %></td>
					<td><%= link_to "詳細画面へ", employee, class: "btn btn-success" %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/employees/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<p><%= flash.notice %></p>
			<h2>会員詳細</h2>
			<table class="table">
				<tr>
					<th>名前</th>
					<td><%= @employee.name %></td>
				</tr>
				<tr>
					<th>名前（カナ）</th>
					<td><%= @employee.name_kana %></td>
				</tr>
				<tr>
					<th>生年月日</th>
					<td><%= @employee.birthday %></td>
				</tr>
				<tr>
					<th>メールアドレス</th>
					<td><%= @employee.email %></td>
				</tr>
				<tr>
					<td><%= link_to "情報編集", edit_employee_path, class: "btn btn-success form-control" %></td>
					<td><%= link_to "退会する", employee_path, method: :delete, data: { confirm: '本当に退会しますか？'}, class: "btn btn-danger form-control" %></td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-9">
		<h2>チャット中のお店一覧</h2>
			<table class="table">
				<tr>
					<th>お店の名前</th>
					<th>給与</th>
					<th>場所</th>
					<th>求人数</th>
					<th></th>
					<th></th>
				</tr>
				<%= @chat.each do |chat| %>
					<tr>
						<td><%= chat.name %></td>
						<td><%= chat.salary %></td>
						<td><%= chat.location %></td>
						<td><%= chat.offering %></td>
						<td><%= link_to "チャットを削除", chat_path, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger" %></td>
						<td><%= link_to "チャットする", chat, class: "btn btn-info" %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>