config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
  	sessions: "employees/sessions", registrations: "employees/registrations", passwords: "employees/passwords"
  }
  devise_for :companies, path: 'companies', controllers: {
  	sessions: "companies/sessions", registrations: "companies/registrations", passwords: "companies/passwords"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies, except: [:new, :create, :index]
  resources :employees, except: [:new, :create]
  root to: 'companies#index'

  resources :chats, except: [:edit]
  resources :messages, only: [:index, :new, :create]
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :validatable, :trackable
	has_many :chats
	has_many :messages
	enum status: {release: true, nonrelease: false}
	attachment :image

	validates :introduction, length: { maximum: 120 }
	validates :tell, numericality: { only_integer: true }
	validates :post_code, numericality: { only_integer: true }
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :tell, :post_code, :address, :location, :image_id, :introduction, :salary, :condition, :offering, :status, :admin])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  before_action :authenticate_company!
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :name_kana, :tell, :post_code, :address, :location, :image_id, :introduction, :salary, :condition, :offering, :status, :admin])
  end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :authenticate_company!, except: [:index, :show]

	def index
		@company = Company.where(status: "release").where.not(offering: "0").order('updated_at').reverse_order
		@company_all = Company.all
	end

	def show
		@company = Company.find(params[:id])
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(company_params)
			redirect_to company_path, notice: "情報を編集しました。"
		else
			render :edit
		end
	end

	def destroy
		company = Company.find(params[:id])
		company.destroy
		redirect_to root_path, notice: "情報を削除しました。"
	end

	private
	def company_params
		params.require(:company).permit(:name, :name_kana, :tell, :post_code, :address, :location, :image, :introduction, :salary, :condition, :offering, :status, :admin, :email, :password, :encrypted_password)
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= form_for (@company) do |f| %>
				<table class="table">
					<tr>
						<td><%= f.label :お店の名前 %></td>
						<td><%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "レストラン◯◯ ◯◯店", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :お店の名前（カナ） %></td>
						<td><%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana", placeholder: "レストラン◯◯ ◯◯テン", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :電話番号 %></td>
						<td><%= f.text_field :tell, autofocus: true, autocomplete: "tell", placeholder: "01234567890 ハイフン無しで入力", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :メールアドレス %></td>
						<td><%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "example@example.com", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :郵便番号 %></td>
						<td><%= f.text_field :post_code, autofocus: true, autocomplete: "post_code", placeholder: "0000000 ハイフン無しで入力", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :住所 %></td>
						<td><%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: "東京都◯◯区◯◯ 0-0-0", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :場所 %></td>
						<td><%= f.text_field :location, autofocus: true, autocomplete: "location", placeholder: "◯◯駅から徒歩◯◯分", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :給与 %></td>
						<td>時給<%= f.number_field :salary, :min => "0", :max => "5000" %>円</td>
					</tr>
					<tr>
						<td><%= f.label :写真 %></td>
						<td><%= f.attachment_field :image %></td>
					</tr>
					<tr>
						<td><%= f.label :条件 %></td>
						<td><%= f.text_field :condition, autofocus: true, autocomplete: "condition", placeholder: "週休◯◯日", :required => "required", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :求人 %></td>
						<td><%= f.number_field :offering, :min => "0", :max => "30" %>人</td>
					</tr>
					<tr>
						<td><%= f.label :お店の紹介文 %></td>
						<td><%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", placeholder: "120文字まで", class: "form-control" %></td>
					</tr>
					<tr>
						<td><%= f.label :情報公開 %></td>
						<td><%= f.select :status, [["公開する", "release"], ["非公開にする", "nonrelease"]] %></td>
					</tr>
					<tr>
						<td></td>
						<td><%= f.submit "情報を保存する", class: "btn btn-success" %></td>
					</tr>
				</table>
			<% end %>
		</div>
		<div class="col-md-2"></div>
	</div>
</div>

app/views/companies/index.html.erb
<% content_for :javascript_pack do %>
	<%= javascript_pack_tag 'hello_react' %>
<% end %>
	<div class="main-visual">
		<div class="main-visual-content">
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-9">
				<p><%= flash.notice %></p>
				<% @company.each do |company| %>
					<div class="card text-center">
						<h3 class="card-header"><%= company.name %> (<%= company.name_kana %>)</h3>
						<div class="card-body">
							<h4><%= company.introduction %></h4>
							<table class="table text-center">
								<tbody>
									<tr>
										<td rowspan="7">
											<%= attachment_image_tag company, :image, size: '200x200', fallback: "images.png" %>
										</td>
									</tr>
									<tr>
										<th>給与</th>
										<td>時給<%= company.salary %>円</td>
									</tr>
									<tr>
										<th>場所</th>
										<td><%= company.location %></td>
									</tr>
									<tr>
										<th>条件</th>
										<td><%= company.condition %></td>
									</tr>
									<tr>
										<th>求人数</th>
										<td><%= company.offering %></td>
									</tr>
									<tr>
										<th>電話番号</th>
										<td><%= company.tell %></td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="card-footer">
							<%= link_to "お店の詳細画面へ", company, class: "btn btn-primary" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
<% if company_signed_in? && current_company.admin == true %>
	<div class="container">
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-9">
				<% @company_all.each do |company_all| %>
					<div class="card text-center">
						<h3 class="card-header"><%= company_all.name %> (<%= company_all.name_kana %>)</h3>
						<div class="card-body">
							<h4><%= company_all.introduction %></h4>
							<table class="table text-center">
								<tbody>
									<tr>
										<td rowspan="7">
											<%= attachment_image_tag company_all, :image_id, size: '200x200', fallback: "images.png" %>
										</td>
									</tr>
									<tr>
										<th>給与</th>
										<td><%= company_all.salary %></td>
									</tr>
									<tr>
										<th>場所</th>
										<td><%= company_all.location %></td>
									</tr>
									<tr>
										<th>条件</th>
										<td><%= company_all.condition %></td>
									</tr>
									<tr>
										<th>求人数</th>
										<td><%= company_all.offering %></td>
									</tr>
									<tr>
										<th>電話番号</th>
										<td><%= company_all.tell %></td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="card-footer">
							<% if company_all.status == "release" %>
								<p>公開中</p>
							<% else %>
								<p>非公開中</p>
							<% end %>
							<%= link_to "お店の詳細画面へ", company, class: "btn btn-primary" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>
<div id="app"></div>

app/views/companies/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-9">
			<p><%= flash.notice %></p>
			<h5>情報公開日 : (<%= @company.updated_at %>)</h5>
			<p class="text-center"><%= @company.introduction %></p>
			<table class="table">
				<tr>
					<% if company_signed_in? %>
					<td rowspan="10">
					<% elsif employee_signed_in? %>
					<td rowspan="9">
					<% else %>
					<td rowspan="9">
					<% end %>
						<%= attachment_image_tag @company, :image, size: '300x300', fallback: "images.png" %>
					</td>
					<th colspan="3">
						<%= @company.name %>(<%= @company.name_kana %>)
					</th>
				</tr>
				<tr>
					<th>給与 :</th>
					<td>時給<%= @company.salary %>円</td>
				</tr>
				<tr>
					<th>場所 :</th>
					<td><%= @company.location %></td>
				</tr>
				<tr>
					<th>条件 :</th>
					<td><%= @company.condition %></td>
				</tr>
				<tr>
					<th>求人数 :</th>
					<td><%= @company.offering %></td>
				</tr>
				<tr>
					<th>電話番号 :</th>
					<td><%= @company.tell %></td>
				</tr>
				<tr>
					<th rowspan="2">住所 :</th>
					<td><%= @company.post_code %></td>
				</tr>
				<tr>
					<td><%= @company.address %></td>
				</tr>
				<tr>
					<th>メールアドレス :</th>
					<td><%= @company.email %></td>
				</tr>
				<% if company_signed_in? %>
					<tr>
						<th>情報 :</th>
						<td>
							<% if @company.status == "release" %>
								<p>公開中</p>
							<% else %>
								<p>非公開中</p>
							<% end %>
						</td>
					</tr>
				<% elsif employee_signed_in? %>
				<% end %>
				<tr>
					<th></th>
					<td colspan="2">
						<% if company_signed_in? %>
							<%= link_to "お店情報編集", edit_company_path, class: "btn btn-warning" %>
							<%= link_to "情報削除", company_path, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %>
						<% elsif employee_signed_in? %>
							<%= link_to "チャット開始", chat_path, class: "btn btn-primary" %>
						<% else %>
							<%= link_to "ログインしてチャットする", new_employee_session_path, class: "btn btn-info" %>
						<% end %>
					</td>
				</tr>
			</table>
		</div>
		<div class="col-md-1"></div>
	</div>
</div>