config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
  	sessions: "employees/sessions", registrations: "employees/registrations", passwords: "employees/passwords"
  }
  devise_for :companies, path: 'companies', controllers: {
  	sessions: "companies/sessions", registrations: "companies/registrations", passwords: "companies/passwords"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies, except: [:new, :create, :index]
  resources :employees, except: [:new, :create]
  root to: 'companies#index'

  resources :chats, except: [:edit]
  resources :messages, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
	has_many :messages
	belongs_to :company
	belongs_to :employee
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :validatable, :trackable
	has_many :chats
	has_many :messages
	enum status: {release: true, nonrelease: false}
	attachment :image

	validates :introduction, length: { maximum: 120 }
	validates :tell, numericality: { only_integer: true }
	validates :post_code, numericality: { only_integer: true }
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable, :trackable
    has_many :chats
    has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :chat
	belongs_to :company
	belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		if current_company
			company_path(current_company)
		elsif current_employee
			root_path
		end
	end


	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:admin])
	end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

	before_action :authenticate_company!
	before_action :authenticate_employee!

	def show
		@chat = Chat.find(params[:id])
		@chat
	end

	def new
		@chat = Chat.new
	end

	def create
		@chat = Chat.new
		@chat.save
	end

	def destroy
		chat = Chat.find(params[:id])
		chat.destroy
		redirect_to request.referrer
	end

	def update
	end

	private
	def chat_params
		params.require(:chat).permit(:company_id, :employee_id, :updated_at)
	end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :authenticate_company!, except: [:index, :show]

	def index
		@company = Company.where(status: "release").where.not(offering: "0").order('updated_at').reverse_order
		@company_all = Company.all
	end

	def show
		@company = Company.find(params[:id])
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(company_params)
			redirect_to company_path, notice: "情報を編集しました。"
		else
			render :edit
		end
	end

	def destroy
		company = Company.find(params[:id])
		company.destroy
		redirect_to root_path, notice: "情報を削除しました。"
	end

	private
	def company_params
		params.require(:company).permit(:name, :name_kana, :tell, :post_code, :address, :location, :image, :introduction, :salary, :condition, :offering, :status, :admin, :email, :password, :encrypted_password)
	end
end

app/controllers/concerns/accessible.rb
module Accessible
	extend ActiveSupport::Concern
	included do
		before_action :check_user
	end

	protected
	def check_user
		if current_company
			flash.clear
			redirect_to company_path(current_company) && return
		elsif current_employee
			flash.clear
			redirect_to root_path && return
		end
	end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :authenticate_employee!

	def index
		@employee = Employee.all
	end

	def show
		@employee = Employee.find(params[:id])
		# @age = (Date.today.strftime("%Y/%m/%d").to_i - @employee[:birthday].strftime("%Y/%m/%d").to_i) / 10000
		@chat = Chat.all
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employee_path, notice: "情報を編集しました。"
		else
			render :edit
		end
	end

	def destroy
		employee = Employee.find(params[:id])
		employee.destroy
		redirect_to employee_path, notice: "情報を削除しました。"
	end

	private
	def employee_params
		params.require(:employee).permit(:name, :name_kana, :birthday, :introduction, :admin, :email, :password, :encrypted_password)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		message = Message.all
	end

	def new
		@message = Message.new
	end

	def create
		@message = message.new
		@message.save
	end

	private
	def message_params
		params.require(:message).permit(:company_id, :employee_id, :chat_id, :body, :updated_at)
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	before_action :authenticate_user!, except: [:company, :show]

	def index
		@users = Emplooyee.user.all
	end

	def show
		@user = Employee.user.find(params[:id])
		@age = (Date.today.strftime("%Y%m%d").to_i - @user[:birthday].strftime("%Y%m%d").to_i) / 10000
		@chat = User.chat.where(userable: "company")
	end

	def edit
		@user = User.find(parmas[:id])
	end

	def update
		@user = User.find(parmas[:id])
		if user.update(user_params)
			if @user.userable == company
				redirect_to user_path, notice: "情報を編集しました！"
			elsif @user.userable == employee
				redirect_to company_show_path, notice: "情報を編集しました！"
			elsif @user.admin == true
				redirect_to root_path
			end
		else
			render :edit
		end
	end

	def destroy
		user = User.find(params[:id])
		user.destroy
		redirect_to root_path
	end

	def company
		@users = Company.user.where(status: "release").order('updated_at')
		@user = Company.user.find(params[:id])
	end

	def company_show
		@user = Company.user.find(params[:id])
		@chat = User.chat.where(userable: "employee")
	end

	private
	def user_params
		params.require(:user).permit(:userable, :admin, :email, :encrypted_password, :name, :name_kana, :tell)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :javascript_pack %>
  </head>

  <body>
    <header>
      <div class="container">
        <ul class="nav navbar-nav navbar-left">
          <li>
            <% if company_signed_in? %>
              <%= link_to "jobapp", company_path(current_company), class: "btn btn-lg btn-default" %>
            <% elsif employee_signed_in? %>
              <%= link_to "jobapp", root_path, class: "btn btn-lg btn-default" %>
            <% else %>
              <%= link_to "jobapp", root_path, class: "btn btn-lg btn-default" %>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if company_signed_in? %>
            <li><%= link_to current_company.name, company_path(current_company), class: "btn btn-info" %></li>
            <li><%= link_to 'ログアウト', destroy_company_session_path, method: :delete, class: "btn btn-danger" %></li>
          <% elsif employee_signed_in? %>
            <li><%= link_to current_employee.name, employee_path(current_employee), class: "btn btn-info" %></li>
            <li><%= link_to 'ログアウト', destroy_employee_session_path, method: :delete, class: "btn btn-danger" %></li>
          <% elsif company_signed_in? && current_company.admin == true %>
            <li><%= link_to 'お店一覧', root_path, class: "btn" %></li>
            <li><%= link_to 'ログアウト', destroy_company_session_path, method: :delete, class: "btn btn-danger" %></li>
          <% elsif employee_signed_in? && current_employee.admin == true %>
            <li><%= link_to 'お店一覧', root_path, class: "btn" %></li>
            <li><%= link_to 'ログアウト', destroy_employee_session_path, method: :delete, class: "btn btn-danger" %></li>
          <% else %>
            <li><%= link_to '出店者としてログイン', new_company_session_path, class: "btn btn-default" %></li>
            <li><%= link_to '求職者としてログイン', new_employee_session_path, class: "btn btn-default" %></li>
          <% end %>
        </ul>
      </div>
    </header>
    <div class="main-contents">
    </div>
    <%= yield %>
  </body>
</html>